### ISSUE TITLE
Supporto per DartVM ?

### ISSUE THREAD

**Issue by sandrobilbeisi** [unbit/unbit-docs#8]
Salve a tutti !

c'è qualcuno che abbia già provato ad usare DartVM su piattaforma UnBit tradizionale ?

Io so già usare Dart su server da un paio d'anni .. theory of operation del programma è simile a Node

purtroppo l'uso di Node su UnBit non è ancora documentato

DartVM gira come single-thread single-process e dispone di una sorta di multithreading basato sugli 'isolates' ... molto efficiente e parco nei consumi il processo gira discretamente bene anche con pochi MB occupati in RAM

**Comment by unbit** [comment]
Ciao, la vecchia piattaforma e' ormai fuori supporto da meta' 2017. Tutti i nuovi sviluppi sono nel progetto uwsgi.it
